# Generated by Django 3.2.25 on 2024-08-26 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_devicestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichsu',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
