# Generated by Django 4.2.16 on 2024-09-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240826_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvironmentalData',
        ),
    ]
