# Generated by Django 4.2.16 on 2024-10-01 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_delete_environmentaldata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lichsu',
            old_name='thiet_bi',
            new_name='device',
        ),
        migrations.RenameField(
            model_name='lichsu',
            old_name='trang_thai',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='lichsu',
            old_name='thoi_gian',
            new_name='timestamp',
        ),
    ]
